### ISSUE TITLE
Request failed with status code 429

### ISSUE THREAD

**Issue by MrPatryk** [zerodytrash/TikTok-Live-Connector#135]
Hello, I got error while i try to connect to tiktok live :

```
Failed to connect Error: Request failed with status code 429
    at createError (/home/runner/Nodejs/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/runner/Nodejs/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/home/runner/Nodejs/node_modules/axios/lib/adapters/http.js:312:11)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```
Stream is live, I even tried to update lib and still this error. Any fix?

**Comment by bakteribaik** [comment]
The HTTP 429 Too Many Requests response status code indicates the user has sent too many requests in a given amount of time ("rate limiting")

[Source](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429)
