### ISSUE TITLE
Failed to connect Error: Failed to retrieve room_id from page source.

### ISSUE THREAD

**Issue by kuangm** [zerodytrash/TikTok-Live-Connector#193]
How to resolve project startup errors

Error message：
Failed to connect Error: Failed to retrieve room_id from page source. timeout of 10000ms exceeded
    at WebcastPushConnection._retrieveRoomId2 (D:\Downloads\TikTok-Live-Connector-main\node_modules\tiktok-live-connector\dist\index.js:532:11)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async WebcastPushConnection.connect (D:\Downloads\TikTok-Live-Connector-main\node_modules\tiktok-live-connector\dist\index.js:270:9)

**Comment by Rachael0108** [comment]
請問解決了嗎

**Comment by kuangm** [comment]
> 請問解決了嗎

使用vpn代理即可
