### ISSUE TITLE
when running my server sometimes i get SignatureError: Failed to sign request: Failed to sign request: timeout of 5000ms exceeded

### ISSUE THREAD

**Issue by mika481** [zerodytrash/TikTok-Live-Connector#248]
Attempting to reconnect to mousselinet's stream (Attempt 1)...
[mousselinet] Connection error: {
  info: 'Error while connecting',
  exception: SignatureError: Failed to sign request: Failed to sign request: timeout of 5000ms exceeded; URL: https://webcast.tiktok.com/webcast/im/fetch/?aid=1988&app_language=en-US&app_name=tiktok_web&browser_language=en&browser_name=Mozilla&browser_online=true&browser_platform=Win32&browser_version=5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F106.0.0.0+Safari%2F537.36&cookie_enabled=true&cursor=&internal_ext=&device_platform=web&focus_state=true&from_page=user&history_len=0&is_fullscreen=false&is_page_visible=true&did_rule=3&fetch_rule=1&last_rtt=0&live_id=12&resp_content_type=protobuf&screen_height=1152&screen_width=2048&tz_name=Europe%2FBerlin&referer=https%3A%2F%2Fwww.tiktok.com%2F&root_referer=https%3A%2F%2Fwww.tiktok.com%2F&host=https%3A%2F%2Fwebcast.tiktok.com&webcast_sdk_version=1.3.0&update_version_code=1.3.0&room_id=7451570590274915077; URL: https://webcast.tiktok.com/webcast/im/fetch/?aid=1988&app_language=en-US&app_name=tiktok_web&browser_language=en&browser_name=Mozilla&browser_online=true&browser_platform=Win32&browser_version=5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F106.0.0.0+Safari%2F537.36&cookie_enabled=true&cursor=&internal_ext=&device_platform=web&focus_state=true&from_page=user&history_len=0&is_fullscreen=false&is_page_visible=true&did_rule=3&fetch_rule=1&last_rtt=0&live_id=12&resp_content_type=protobuf&screen_height=1152&screen_width=2048&tz_name=Europe%2FBerlin&referer=https%3A%2F%2Fwww.tiktok.com%2F&root_referer=https%3A%2F%2Fwww.tiktok.com%2F&host=https%3A%2F%2Fwebcast.tiktok.com&webcast_sdk_version=1.3.0&update_version_code=1.3.0&room_id=7451570590274915077
      at signRequest (C:\tiktok\node_modules\tiktok-live-connector\dist\lib\tiktokSignatureProvider.js:120:11)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async TikTokHttpClient._buildUrl2 (C:\tiktok\node_modules\tiktok-live-connector\dist\lib\tiktokHttpClient.js:118:15)     
      at async TikTokHttpClient.getDeserializedObjectFromWebcastApi (C:\tiktok\node_modules\tiktok-live-connector\dist\lib\tiktokHttpClient.js:77:15)
      at async WebcastPushConnection._fetchRoomData2 (C:\tiktok\node_modules\tiktok-live-connector\dist\index.js:607:25)
      at async WebcastPushConnection.connect (C:\tiktok\node_modules\tiktok-live-connector\dist\index.js:300:9) {

**Comment by tinkerbaj** [comment]
Same here
