### ISSUE TITLE
Failed to sign request: Request failed with status code 502

### ISSUE THREAD

**Issue by laisangbum** [zerodytrash/TikTok-Live-Connector#46]
Failed to connect Error: Failed to sign request: Request failed with status code 502; URL: https://webcast.tiktok.com/webcast/im/fetch/?aid=1988&app_language=en-US&app_name=tiktok_web&browser_language=en&browser_name=Mozilla&browser_online=true&browser_platform=Win32&browser_version=5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F102.0.5005.63+Safari%2F537.36&cookie_enabled=true&cursor=&internal_ext=&device_platform=web&focus_state=true&from_page=user&history_len=4&is_fullscreen=false&is_page_visible=true&did_rule=3&fetch_rule=1&identity=audience&last_rtt=0&live_id=12&resp_content_type=protobuf&screen_height=1152&screen_width=2048&tz_name=Europe%2FBerlin&referer=https%3A%2F%2Fwww.tiktok.com%2F&root_referer=https%3A%2F%2Fwww.tiktok.com%2F&version_code=180800&webcast_sdk_version=1.3.0&update_version_code=1.3.0&room_id=7123874059737205509
    at signRequest (/Users/jeremylai/Documents/node/node_modules/tiktok-live-connector/dist/lib/tiktokSignatureProvider.js:81:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async TikTokHttpClient._buildUrl2 (/Users/jeremylai/Documents/node/node_modules/tiktok-live-connector/dist/lib/tiktokHttpClient.js:98:15)
    at async TikTokHttpClient.getDeserializedObjectFromWebcastApi (/Users/jeremylai/Documents/node/node_modules/tiktok-live-connector/dist/lib/tiktokHttpClient.js:63:15)
    at async WebcastPushConnection._fetchRoomData2 (/Users/jeremylai/Documents/node/node_modules/tiktok-live-connector/dist/index.js:500:25)
    at async WebcastPushConnection.connect (/Users/jeremylai/Documents/node/node_modules/tiktok-live-connector/dist/index.js:269:7)

**Comment by linhnguyen9988** [comment]
@laisangbum you need login TikTok first

**Comment by zerodytrash** [comment]
The error was caused by a temporary failure. It should be fixed.

**Comment by xlzengin** [comment]
still have this probleam.does it fix?

**Comment by huyhai** [comment]
it happened again
